# Generated by Django 5.0.6 on 2024-07-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_status'),
        ('checkout', '0002_order_order_number_order_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking'),
        ),
    ]
