# Generated by Django 5.0.6 on 2024-06-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Cottage', 'Cottage'), ('Villa', 'Villa'), ('House', 'House'), ('Loft', 'Loft'), ('Flat', 'Flat')], max_length=50)),
                ('num_bedrooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('amenities', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('availability_calendar', models.TextField()),
            ],
        ),
    ]
