# Generated by Django 5.0.6 on 2024-06-27 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='num_bathrooms',
            new_name='max_guests',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='num_bedrooms',
            new_name='number_of_bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='availability_calendar',
        ),
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.AddField(
            model_name='property',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='London', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='host',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_bedrooms',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(default='S10 1NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='Greater London', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='properties.amenity'),
        ),
    ]
