# Generated by Django 5.0.6 on 2024-06-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_amenity_icon_amenity_font_awesome_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
