# Generated by Django 5.0.6 on 2024-06-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_amenity_options_alter_property_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AddField(
            model_name='amenity',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
