# Generated by Django 5.0.6 on 2024-07-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_amenity_options_amenity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pets_allowed',
        ),
    ]
