# Generated by Django 5.0.6 on 2024-07-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rating',
        ),
        migrations.AddField(
            model_name='property',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
