# Generated by Django 5.0.6 on 2024-07-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_check_in_date_booking_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nights',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(),
        ),
    ]
