# Generated by Django 5.0.6 on 2024-07-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_nights_booking_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='nights',
            new_name='total_nights',
        ),
    ]
